trigger:
  - main

pool:
  vmImage: ubuntu-latest
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      inputs:
        script: |
          npm install
    - task: CmdLine@2
      displayName: 'Install snyk-to-html and jq'
      inputs:
        script: 
          npm install -g snyk-to-html jq
          npm install -g commander


    - task: CmdLine@2
      displayName: 'snyk install & auth'
      inputs:
        script: |
          npm install -g snyk snyk-to-html
          mkdir html
          snyk auth $(SNYK_TOKEN)
          # explicitly allow scripts to continue if errors occur
          set +e
    

    - task: CmdLine@2
      displayName: 'Repository Scan'
      inputs:
       script: |
        REPO_NAME="deepaklohar/snyk"
        TAGS=$(curl -s https://hub.docker.com/repository/docker/$REPO_NAME/tags | jq -r '.[].name')
        echo "cat $TAGS"
        for TAG in $TAGS; do
         snyk container test $REPO_NAME:$TAG --json-file-output=results-$TAG.json || true
         RESULT=$?
         snyk-to-html -o $(Build.ArtifactStagingDirectory)/results-container-$TAG.html < results-$TAG.json || true
         if [ $RESULT -ne 0 ]; then exit $RESULT; fi
         done
         snyk monitor || true
      continueOnError: true

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
