trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  group: Authentication
  IMAGE_TAGS: ''

stages:
  
  - stage: Install_Dependencies 
    jobs:
      - template : Install_Dependencies_Template.yml
      
  - stage: SAST
    jobs:
    - template : SAST.yml

  - stage: SCA
    jobs:
      - template: sca.yml
       
  - stage: Container_Scan
    jobs:
     - template: azure-pipelines-3.yml

  - stage: Multiple_Container_Scan
    jobs:
      - job: Multiple_Container_Scan
        steps:
        - task: CmdLine@2
          displayName: 'Run Python script to generate image tags'
          inputs:
            script: |
              python dockerImageTags.py 
              python -c "
              import yaml
              with open('Tags.yaml', 'r') as file:
                data = yaml.safe_load(file)"
                print(data)
              #print(f"##vso[task.setvariable variable=IMAGE_TAGS]{{data['tags']}}")
        - script: |
            echo "Using image tags: $(IMAGE_TAGS)"
          displayName: 'Use image tags in pipeline step'
