trigger:
  - main

pool:
  name: 'Default'  # Replace with the actual name of your agent pool if different
  demands:
  - agent.name -equals Deepaks-MacBook-Pro

steps:
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdkVersion)
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'
