trigger:
  - main

pool:
  vmImage: ubuntu-latest


stages:
  - stage: Install Dependencies 
    jobs:
      - job: Install_Dependecies
        steps:
          - # install Dependency for snyk container scan
        - task: NodeTool@0
          inputs:
            versionSpec: '12.x'
          displayName: 'Install Node.js'
          - task: CmdLine@2
            inputs:
              script: 'npm install'
          - task: CmdLine@2
            displayName: 'Install Python Dependencies'
            inputs:
              script: |
                sudo apt update
                sudo apt install -y python3 python3-pip
                python3 -m pip install --upgrade pip
                python3 -m pip install requests
                echo "Installing pyyaml..."
                pip install pyyaml
  
  - stage: SAST
    jobs:
      - job: SAST
        steps:
        - task: CmdLine@2
          displayName: 'Snyk Code Scan'
          inputs:
            script: |
              snyk code test --sarif-file-output=results.sarif || true
              RESULT=$?
              snyk-to-html -o $(Build.ArtifactStagingDirectory)/results-code.html < results.sarif || true
              snyk monitor || true	
              exit $RESULT
          continueOnError: true
          
        
        
   