    jobs:
      - job: Container_Scan
        steps:
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: 'Snyk Authentication'
            testType: 'container'
            dockerImageName: 'deepaklohar/petclini:V2'
            #dockerImageName: 'deepaklohar/snyk:Webgoat'
            dockerfilePath: 'Dockerfile'
            monitorWhen: 'always'
            failOnIssues: false
          condition: succeededOrFailed()