trigger:
- main

pool:
  name: 'Default'
  demands:
  - agent.name -equals Deepaks-MacBook-Pro  # Ensure this matches your agent name
  - maven  # Demand Maven to be available on the agent

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your Maven POM file

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'  # Path to your Maven POM file
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'  # Specify JDK version to use
    jdkVersionOption: '21.0'  # Adjust this to the JDK version you want to use
    mavenVersionOption: 'Default'  # Use default Maven version
    mavenAuthenticateFeed: false  # Whether to authenticate Maven feeds (adjust based on your setup)
    effectivePomSkip: false  # Set to true to skip processing of effective POM
    sonarQubeRunAnalysis: false  # Whether to run SonarQube analysis
