- job: SCA
        steps:
        - task: SnykSecurityScan@1
          inputs:
            serviceConnectionEndpoint: 'Snyk Authentication'
            testType: 'app'
            monitorWhen: 'always'
            failOnIssues: true
          condition: succeededOrFailed()
          displayName: "SCA"