pool:
  vmImage: ubuntu-latest

variables:
  group: Authentication
  IMAGE_TAGS: ''

stages:
  
  - stage: Install_Dependencies 
    jobs:
      - template : Install_Dependencies_Template.yml
      
  - stage: SAST
    jobs:
    - template : SAST.yml

  - stage: SCA
    jobs:
      - template: sca.yml
       
  - stage: Container_Scan
    jobs:
     - template: cscan.yml
