trigger:
  - main

pool:
  vmImage: ubuntu-latest
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'
    - task: CmdLine@2
      inputs:
        script: |
          npm install
    - task: CmdLine@2
      displayName: 'snyk install & auth'
      inputs:
        script: |
          npm install -g snyk snyk-to-html
          mkdir html
          snyk auth 173f3477-cac0-44a8-a51d-0337b7f37003
          # explicitly allow scripts to continue if errors occur
          set +e
          snyk code test --sarif-file-output=results.sarif || true
          RESULT=$?
          snyk-to-html -o $(Build.ArtifactStagingDirectory)/results-code.html < results.sarif || true
          exit $RESULT
          continueOnError: true
          displayName: 'snyk code'

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenOptions: '-Xmx3072m'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
